#!/usr/bin/env python3
"""
Build energy-per-operation vs transition-frequency plots for the 2LAL and
ECRL experiments, in the same form the ECRL work already used.

For each CSV it emits:
  <name>.cir   ngspice plot deck, same style as
               ecrl_exp1/ecrl_energy_vs_transition_frequency.cir
               (run with:  ngspice <name>.cir)
  <name>.png   gnuplot render, for viewing without an X session

Plus one overlay PNG comparing the two families at a chosen width.
"""
import csv, subprocess, sys, os

WIDTHS = ["0.84", "1.0", "1.2", "1.5", "2.0", "3.0"]
VECNAME = {"0.84": "E084", "1.0": "E100", "1.2": "E120",
           "1.5": "E150", "2.0": "E200", "3.0": "E300"}

def load(path, xaxis="f_tr"):
    """-> {width: [(x_MHz, E_fJ), ...] sorted by x}

    xaxis="f_tr"    -> transition frequency  = 1/Tphase
    xaxis="f_clock" -> power-clock frequency = 1/(4*Tphase) = the OPERATION rate

    These differ by exactly 4x.  Energy is per power-clock cycle per gate in
    both cases, so only the x-axis changes -- no data point moves vertically.
    """
    d = {w: [] for w in WIDTHS}
    with open(path) as f:
        for row in csv.DictReader(f):
            w = row["W_um"]
            if w not in d:
                continue
            tph = float(row["Tphase_ns"])
            x = 1000.0 / tph if xaxis == "f_tr" else 1000.0 / (4.0 * tph)
            d[w].append((x, float(row["E_C_fJ"])))
    for w in d:
        d[w].sort()
    return d

def write_cir(data, out, title, xlab='transition frequency f_tr = 1/TPHASE  (MHz)'):
    n = len(data[WIDTHS[0]])
    L = ["* " + "="*60, "* " + title,
         "*", "* X-axis : %s" % xlab,
         "* Y-axis : energy per operation (fJ)",
         "*", "* Generated by make_plots.py from the sweep CSV -- do not hand-edit.",
         "* " + "="*60, "", ".control", "", "set noaskquit", "",
         "let FTR = vector(%d)" % n]
    for i, (f, _) in enumerate(data[WIDTHS[0]]):
        L.append("let FTR[%d] = %g" % (i, f))
    for w in WIDTHS:
        v = VECNAME[w]
        L += ["", "* W = %s um" % w, "let %s = vector(%d)" % (v, n)]
        for i, (_, e) in enumerate(data[w]):
            L.append("let %s[%d] = %.6g" % (v, i, e))
    L += ["", "print FTR"] + ["print %s" % VECNAME[w] for w in WIDTHS]
    L += ["", "plot " + " ".join("%s vs FTR" % VECNAME[w] for w in WIDTHS),
          "", ".endc", "", ".end", ""]
    open(out, "w").write("\n".join(L))

def write_png(data, out, title, xlab=None, xlo=8, xhi=1300, xtics=None):
    xtics = xtics or '("10" 10, "20" 20, "50" 50, "100" 100, "200" 200, "500" 500, "1000" 1000)'
    xlab = xlab or 'Transition frequency  f_tr = 1/TPHASE   (MHz)'
    dat = out + ".dat"
    with open(dat, "w") as f:
        f.write("# f_tr_MHz " + " ".join("W%s" % w for w in WIDTHS) + "\n")
        for i in range(len(data[WIDTHS[0]])):
            f.write("%g " % data[WIDTHS[0]][i][0])
            f.write(" ".join("%.6g" % data[w][i][1] for w in WIDTHS) + "\n")
    plots = ", ".join(
        "'%s' using 1:%d with linespoints lw 2 pt %d title 'W = %s um'"
        % (dat, i + 2, i + 4, w) for i, w in enumerate(WIDTHS))
    gp = f"""
set terminal pngcairo size 1100,760 font "Sans,11"
set output '{out}'
set title "{title}" font "Sans,12"
set xlabel "{xlab}"
set ylabel "Energy per operation  (fJ)"
set logscale x
set grid
set key top left
set xtics {xtics}
set xrange [{xlo}:{xhi}]
plot {plots}
"""
    subprocess.run(["gnuplot"], input=gp, text=True, check=True)

def overlay(sets, out, title, width="1.0", xlab=None, xlo=8, xhi=1300, xtics=None):
    xtics = xtics or '("10" 10, "20" 20, "50" 50, "100" 100, "200" 200, "500" 500, "1000" 1000)'
    xlab = xlab or 'Transition frequency  f_tr = 1/TPHASE   (MHz)'
    files, plots = [], []
    for i, (label, data) in enumerate(sets):
        dat = "%s.%d.dat" % (out, i)
        with open(dat, "w") as f:
            for fr, e in data[width]:
                f.write("%g %.6g\n" % (fr, e))
        files.append(dat)
        plots.append("'%s' using 1:2 with linespoints lw 3 pt %d title '%s'"
                     % (dat, i + 4, label))
    gp = f"""
set terminal pngcairo size 1100,760 font "Sans,11"
set output '{out}'
set title "{title}" font "Sans,12"
set xlabel "{xlab}"
set ylabel "Energy per operation  (fJ)"
set logscale x
set grid
set key top left
set xtics {xtics}
set xrange [{xlo}:{xhi}]
plot {', '.join(plots)}
"""
    subprocess.run(["gnuplot"], input=gp, text=True, check=True)

if __name__ == "__main__":
    jobs = [
        ("2lal_inverter_sweep.csv", "2lal_energy_vs_ftr",
         "2LAL quad-rail inverter (8-stage ring): energy per operation vs transition frequency\\nsky130 tt, VDD 1.8 V, L = 0.15 um, CL = 25 fF per node"),
        ("ecrl_exp1/ecrl_slowramp_sweep.csv", "ecrl_slowramp_energy_vs_ftr",
         "ECRL inverter (adiabatic slow-ramp input, alternating data): energy per operation vs transition frequency\\nsky130 tt, VDD 1.8 V, L = 0.15 um, CL = 25 fF"),
    ]
    loaded = []
    for csvp, stem, title in jobs:
        if not os.path.exists(csvp):
            sys.exit("missing %s" % csvp)
        d = load(csvp)
        write_cir(d, stem + ".cir", title)
        write_png(d, stem + ".png", title)
        loaded.append((stem, d))
        print("wrote %s.cir and %s.png" % (stem, stem))

    overlay([("ECRL inverter (slow-ramp input)", loaded[1][1]),
             ("2LAL quad-rail inverter (ring)",   loaded[0][1])],
            "ecrl_vs_2lal_W1.0.png",
            "ECRL vs 2LAL inverter, matched conditions\\nW = 1.0 um, L = 0.15 um, CL = 25 fF, same TPHASE, alternating data")
    print("wrote ecrl_vs_2lal_W1.0.png")

    # ---- same data against the POWER-CLOCK frequency = the operation rate ----
    XL = "Power-clock frequency  f_clock = 1/(4*TPHASE)  =  operation rate   (MHz)"
    fc = []
    for csvp, stem, title in jobs:
        d = load(csvp, xaxis="f_clock")
        stem2 = stem.replace("_vs_ftr", "_vs_fclock")
        t2 = title.replace("vs transition frequency", "vs power-clock frequency")
        write_cir(d, stem2 + ".cir", t2, xlab=XL)
        write_png(d, stem2 + ".png", t2, xlab=XL, xlo=2, xhi=330, xtics='("2.5" 2.5, "5" 5, "12.5" 12.5, "25" 25, "50" 50, "125" 125, "250" 250)')
        fc.append(d)
        print("wrote %s.cir and %s.png" % (stem2, stem2))
    overlay([("ECRL inverter (slow-ramp input)", fc[1]),
             ("2LAL quad-rail inverter (ring)",   fc[0])],
            "ecrl_vs_2lal_W1.0_fclock.png",
            "ECRL vs 2LAL inverter vs POWER-CLOCK frequency (the operation rate)\\nW = 1.0 um, L = 0.15 um, CL = 25 fF, alternating data",
            xlab=XL, xlo=2, xhi=330, xtics='("2.5" 2.5, "5" 5, "12.5" 12.5, "25" 25, "50" 50, "125" 125, "250" 250)')
    print("wrote ecrl_vs_2lal_W1.0_fclock.png")
