#!/usr/bin/env python3
"""
Generate 2LAL_inverter_ring.sp: the 2LAL quad-rail inverter as a closed
8-stage ring, the way DeBenedictis builds every 2LAL testbench
(4lc/2L.cir TWOCYCLEALL, Shift/sS2.cir, Shift/sQ2.cir).

Why a ring: a 2LAL node is restored by the NEXT stage's reverse gates, so
the last node of an open chain is never restored.  It stays charged, keeps
the previous stage's reverse gates on, and corrupts the stages before it.
A ring has no last node.

The deck is generated because it is 16 cells, 32 loads, 32 initial
conditions and 96 functional checks that all follow from one rule; writing
them by hand invites exactly the index slips they exist to catch.
Edit this script, not the .sp file.  Top-level .param values (WN, WP,
TPHASE, CL, ...) can still be changed in the .sp directly, which is what
run_2lal_sweep.sh does.

    python3 make_2lal_ring.py        # -> 2LAL_inverter_ring.sp
"""

N = 8          # stages in the ring; must be a multiple of 4 so node m and
               # node m+N ride the same rail phase
PERIODS_CHECKED = (3, 4)   # two consecutive rail periods -> every node sees
                           # both data waves, one TRUE on each sub-chain
OUT = "2LAL_inverter_ring.sp"

assert N % 4 == 0 and N >= 8


def rail(m):
    return m % 4


# ---------------------------------------------------------------- data seed
# At t=0 the rails are p0=0 (about to rise), p1=0, p2=VDD (about to fall),
# p3=VDD (flat high).  A TRUE node follows its rail, so only nodes on p2/p3
# can be mid-pulse.  Node m sits on rail m%4, so the ring holds N/4 data
# waves, each occupying one p2 node and the p3 node after it.
#
# Every stage crosses the sub-chains, so a wave's pulse is on sub-chain a at
# even nodes and on n at odd nodes (or the reverse).  Consecutive waves get
# opposite polarity, so at any fixed node the data alternates every rail
# period -- the ring equivalent of the old 1,0,1,0 input.
def wave_is_a_at_even(w):
    return w % 2 == 0


def true_chain_at_t0(m):
    """'a', 'n', or None (both sub-chains at rest) for node m at t=0."""
    if rail(m) not in (2, 3):
        return None
    w = m // 4
    a_even = wave_is_a_at_even(w)
    return "a" if (m % 2 == 0) == a_even else "n"


def true_chain(m, P):
    """Sub-chain carrying the pulse at node m during rail period P.

    Node m's pulse in period P rises at P*TRAIL + (m%4)*TPHASE.  Waves move
    one node per TPHASE, i.e. 4 nodes per period, so the wave there is the
    one that was 4P + (m%4) + 1 ... traced back to its t=0 position.
    """
    k = rail(m)
    # plateau of node m in period P is at tick 4P + k + 1.5; at tick 0.5 a
    # wave sits on each p3 node (m0 = 4w+3).  Ticks elapsed = 4P + k + 1.
    s = 4 * P + k + 1
    m0 = (m - s) % N               # where this wave's pulse was at tick 0.5
    assert rail(m0) == 3
    w = m0 // 4
    a_even = wave_is_a_at_even(w)
    # the wave has crossed s stages since then; parity of node index tracks it
    return "a" if (m % 2 == 0) == a_even else "n"


# sanity: true_chain() at the p3 nodes in period -1 must equal the seed
for m in range(N):
    if rail(m) == 3:
        assert true_chain(m, -1) == true_chain_at_t0(m)


L = []
w = L.append

w(f"""* ==========================================================================
* 2LAL QUAD-RAIL INVERTER -- {N}-STAGE RING
* sky130 / ngspice.  Companion to ecrl_exp1/ecrl_slowramp.sp.
* GENERATED by make_2lal_ring.py -- edit the generator, not this file.
* (Changing a top-level .param value here is fine; run_2lal_sweep.sh does.)
* --------------------------------------------------------------------------
* Replaces the open chain in 2LAL_inverter_multi_test.sp.
*
* WHY A RING
*   A 2LAL node is charged by the stage before it and restored to rest by
*   the stage AFTER it (that stage's reverse gates, switched on by the next
*   node).  The last node of an open chain has no stage after it, so it is
*   never restored; it keeps the previous stage's reverse gates on and
*   corrupts the stages before it.  In the open-chain deck this reached the
*   metered stage 4 and inflated the energy up to 47x at slow clocks.
*   A ring has no last node.  DeBenedictis tests 2LAL the same way
*   (4lc/2L.cir TWOCYCLEALL: 'cyclic shift register, data by
*   initialization'; Shift/sS2.cir and sQ2.cir).
*
* WHAT IS DIFFERENT FROM THE OPEN CHAIN
*   - no ideal input source: data is loaded by .ic and circulates
*   - no unmetered driver/load stages: all {N} stages are metered, so every
*     joule the rails deliver or recover is counted
*   - phi2 / phi3 are written as the inverse of phi0 / phi1 so all four
*     rails are already in steady state at t=0 (a delayed PULSE sits at 0
*     until its delay expires, which is not where phi2/phi3 should be)
*
* AXES (unchanged, 1:1 with the ECRL experiment)
*     TPHASE = transition time,  TRAIL = 4*TPHASE,  f_tr = 1/TPHASE
*     WN = WP, L = 0.15 um, CL on every dual-rail node
*
* WHAT AN 'OPERATION' IS
*   One quad-rail column = the a-cell plus the n-cell at one stage index
*   = 16 FETs.  For ANY data value exactly one of its two sub-chains pulses,
*   so each column switches once per rail period.  {N} columns x one rail
*   period = {N} operations.
*
* SIGNAL ENCODING
*   A dual-rail pair (T,C) rests at FALSE = (0, VDD).  TRUE = T follows its
*   rail phi_m up and back down while C follows the antiphase rail phi_m+2.
* ==========================================================================

.include "./sky130_01v8_tt_fast.spice"

* ---------------------------------------------------------------- parameters
.param VDD    = 1.8
.param WN     = 1.0         ; nFET width, MICRONS   ; SWEEPVAR
.param WP     = 1.0         ; pFET width, MICRONS   ; SWEEPVAR
.param L      = 0.15        ; channel length, MICRONS
.param CL     = 25f         ; load per dual-rail node (matches ECRL's CL)

.param TPHASE = 10n                                 ; SWEEPVAR
.param TRAIL  = '4*TPHASE'  ; one full trapezoid    (== ECRL Tclock)
.param TSTEP  = 'TPHASE/500'
.param TSTOP  = '6*TRAIL+TPHASE'   ; margin: e6 is read AT 6*TRAIL

.options reltol=1e-4 abstol=1e-13 vntol=1e-7 chgtol=1e-16 gmin=1e-14
.options method=gear maxord=2

Vnb vnb 0 DC 0
Vpb vpb 0 DC {{VDD}}

* ---------------------------------------------------------------- power clocks
* rise / flat-high / fall / flat-low of one TPHASE each: 50% duty at the
* midpoint, 25% transition time -- Fig. 1 of the 2LAL paper.
* phi2 = VDD - phi0 and phi3 = VDD - phi1 exactly; writing them that way
* (start high, fall first) puts every rail in steady state from t=0.
* At t=0:  phi0 = 0 rising,  phi1 = 0,  phi2 = VDD falling,  phi3 = VDD.
Vp0 p0 0 PULSE(0     {{VDD}} 0        {{TPHASE}} {{TPHASE}} {{TPHASE}} {{TRAIL}})
Vp1 p1 0 PULSE(0     {{VDD}} {{TPHASE}} {{TPHASE}} {{TPHASE}} {{TPHASE}} {{TRAIL}})
Vp2 p2 0 PULSE({{VDD}} 0     0        {{TPHASE}} {{TPHASE}} {{TPHASE}} {{TRAIL}})
Vp3 p3 0 PULSE({{VDD}} 0     {{TPHASE}} {{TPHASE}} {{TPHASE}} {{TPHASE}} {{TRAIL}})

* ==========================================================================
* CELLS
* ==========================================================================
* Transmission gate: conducts s->d when the dual-rail control (gn,gp) is TRUE.
.subckt TG d gn gp s vnb vpb
xN d gn s vnb sky130_fd_pr__nfet_01v8 w={{WN}} l={{L}}
+ as='WN*L*1.77' ad='WN*L*1.77' ps='(WN+L)*2.4' pd='(WN+L)*2.4'
xP d gp s vpb sky130_fd_pr__pfet_01v8 w={{WP}} l={{L}}
+ as='WP*L*1.77' ad='WP*L*1.77' ps='(WP+L)*2.4' pd='(WP+L)*2.4'
.ends TG

* The 2LAL delay element (Fig 2c / 4lc PHAS2), 8 FETs:
*   forward pair drives the output from phi_t and its antiphase phi_t+2;
*   reverse pair restores the PREVIOUS stage's node from phi_t-1 / phi_t+1
*   once this stage's output is valid.
* Same connections as PHAS2 in DeBenedictis 4lc/2L.cir.
.subckt BUF8P inT inC outT outC L0 L1 L2 L3 vnb vpb
XF1 outT inT inC L1 vnb vpb TG          ; TRUE -> outT pulses on phi_t
XF2 outC inT inC L3 vnb vpb TG          ; TRUE -> outC pulled down by phi_t+2
XR1 inT  outT outC L0 vnb vpb TG        ; restore inT via phi_t-1
XR2 inC  outT outC L2 vnb vpb TG        ; restore inC via phi_t+1
.ends BUF8P

* ==========================================================================
* QUAD-RAIL INVERTER RING
* ==========================================================================
* Node m rides rail phi_(m mod 4).  Stage m takes node m to node m+1
* (mod {N}) and is clocked (L0..L3) = phi_m .. phi_m+3.
* Every stage takes its input from the OPPOSITE sub-chain -- that crossing
* is the inversion.  {N} crossings per lap is even, so the ring is
* logically consistent.

* -------- rail ammeters (0 V sources used as current probes) ---------------
Vm0 p0 r0 DC 0
Vm1 p1 r1 DC 0
Vm2 p2 r2 DC 0
Vm3 p3 r3 DC 0
""")

for m in range(N):
    nxt = (m + 1) % N
    rails = " ".join(f"r{(m + j) % 4}" for j in range(4))
    w(f"* stage {m}  (phi{rail(m)} -> node {nxt} on phi{rail(nxt)})")
    w(f"XP{m} nT{m} nC{m} aT{nxt} aC{nxt} {rails} vnb vpb BUF8P")
    w(f"XN{m} aT{m} aC{m} nT{nxt} nC{nxt} {rails} vnb vpb BUF8P")

w("\n* ---------------------------------------------------------------- node loads")
for m in range(N):
    for s in ("a", "n"):
        for r in ("T", "C"):
            w(f"C{s}{r}{m} {s}{r}{m} 0 {{CL}}")

w("""
* ==========================================================================
* ENERGY INTEGRATOR
* ==========================================================================
* A behavioural current source pushing P(t) into a 1 F capacitor makes V(e)
* the running integral of power, so the node reads directly in JOULES.
Be 0 e I = V(r0)*I(Vm0) + V(r1)*I(Vm1) + V(r2)*I(Vm2) + V(r3)*I(Vm3)
Ce e 0 1
Re e 0 1e15

* ---------------------------------------------------------------- data seed
* Nodes on phi0/phi1 are at rest at t=0 whatever they carry (their rails are
* at 0).  Each p2 node and the p3 node after it hold one data wave:
*   TRUE sub-chain  -> T = VDD (its rail), C = 0 (the antiphase rail)
*   other sub-chain -> at rest, T = 0, C = VDD
* Successive waves have opposite polarity, so each node's data alternates
* every rail period.  To test a constant pattern instead, give every wave
* the same polarity (swap a<->n on the .ic lines of every other wave).""")
w(".ic V(e)=0")
for m in range(N):
    tc = true_chain_at_t0(m)
    parts = []
    for s in ("a", "n"):
        if s == tc:
            parts.append(f"V({s}T{m})={{VDD}} V({s}C{m})=0")
        else:
            parts.append(f"V({s}T{m})=0 V({s}C{m})={{VDD}}")
    tag = f"   ; wave {m // 4}, TRUE on {tc}" if tc else ""
    w(f".ic {' '.join(parts)}{tag}")

w("""
.tran {TSTEP} {TSTOP} uic

* ==========================================================================
* FUNCTIONAL CHECKS
* ==========================================================================
* For every node, in two consecutive rail periods (so it carries both data
* polarities), with ts = start of that node's pulse = P*TRAIL + (m%4)*TPHASE:
*   TRUE sub-chain : T high and C low mid-plateau   (ts + 1.5*TPHASE)
*                    T low and C high mid-rest      (ts + 3.5*TPHASE)
*   other sub-chain: T never rises, C never falls   (MAX/MIN over ts..ts+4T)
* chkhi_* must read > 0.9*VDD, chklo_* must read < 0.1*VDD.
* run_2lal_sweep.sh enforces both at every sweep point.""")
nchk = 0
for P in PERIODS_CHECKED:
    for m in range(N):
        k = rail(m)
        t = true_chain(m, P)
        f = "n" if t == "a" else "a"
        ts = f"{P}*TRAIL+{k}*TPHASE"
        pl = f"'{ts}+1.5*TPHASE'"
        lo = f"'{ts}+3.5*TPHASE'"
        te = f"'{ts}+4*TPHASE'"
        tag = f"{m}_p{P}"
        w(f"* node {m}, period {P}: TRUE on {t}")
        w(f".meas tran chkhi_{t}T{tag}_plat FIND V({t}T{m}) AT={pl}")
        w(f".meas tran chklo_{t}C{tag}_plat FIND V({t}C{m}) AT={pl}")
        w(f".meas tran chklo_{t}T{tag}_rest FIND V({t}T{m}) AT={lo}")
        w(f".meas tran chkhi_{t}C{tag}_rest FIND V({t}C{m}) AT={lo}")
        w(f".meas tran chklo_{f}T{tag}_max MAX V({f}T{m}) FROM='{ts}' TO={te}")
        w(f".meas tran chkhi_{f}C{tag}_min MIN V({f}C{m}) FROM='{ts}' TO={te}")
        nchk += 6

w(f"""
* ==========================================================================
* ENERGY -- {N} columns, one operation each per rail period
* ==========================================================================
* Rail periods 0-1 are left to settle; 2..5 are measured.
.meas tran e2 FIND V(e) AT='2*TRAIL'
.meas tran e3 FIND V(e) AT='3*TRAIL'
.meas tran e4 FIND V(e) AT='4*TRAIL'
.meas tran e6 FIND V(e) AT='6*TRAIL'
* E_A: rail period 2 alone        ({N} operations)
.meas tran E_A PARAM='(e3-e2)/{N}'
* E_B: rail period 3 alone        ({N} operations) -- must match E_A if settled
.meas tran E_B PARAM='(e4-e3)/{N}'
* E_C: periods 2..5, the reported value ({4 * N} operations)
.meas tran E_C PARAM='(e6-e2)/{4 * N}'

* -------- run check -----------------------------------------------------
* p1 starts rising at TPHASE and takes TPHASE to reach VDD, so it crosses
* VDD/2 at exactly 1.5*TPHASE.  run_2lal_sweep.sh reads this back to prove
* the simulator used the TPHASE the sweep asked for.
.meas tran chk_tphase WHEN V(p1)='VDD/2' RISE=1

.end""")

open(OUT, "w").write("\n".join(L) + "\n")
print(f"wrote {OUT}: {N} stages, {N * 16} FETs, {nchk} functional checks")
